# Generated by Django 4.2 on 2023-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
