# Generated by Django 4.2 on 2023-04-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_app', '0003_comic_description_comic_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
