# Generated by Django 4.2 on 2023-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_app', '0004_alter_comic_description_alter_comic_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
