# Generated by Django 4.2 on 2023-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_app', '0005_alter_comic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic', models.ManyToManyField(to='cc_app.comic')),
            ],
        ),
    ]
