# Generated by Django 4.2 on 2023-04-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_app', '0006_favoriteslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('is_gift', models.BooleanField()),
                ('gift_message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
