# Generated by Django 4.2 on 2023-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_app', '0008_customuser_favorites_list_customuser_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorites_list',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_comics',
            field=models.ManyToManyField(related_name='users', to='cc_app.comic'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='FavoritesList',
        ),
    ]
