# Generated by Django 4.2 on 2023-04-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_app', '0009_remove_customuser_favorites_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_gift', models.BooleanField()),
                ('gift_message', models.CharField(max_length=500)),
                ('item', models.ManyToManyField(related_name='cart_item', to='cc_app.comic')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='items',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cart_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cc_app.cartitem'),
        ),
    ]
