# Generated by Django 4.2 on 2023-04-26 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_app', '0010_cartitem_remove_customuser_items_delete_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gift', models.BooleanField()),
                ('gift_message', models.CharField(max_length=500)),
                ('item', models.ManyToManyField(related_name='cart_item', to='cc_app.comic')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cart_item',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.AddField(
            model_name='order',
            name='purchaser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
